version: "3.3"

services:
  database:
    container_name: database
    image: postgres:13.10
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=onidata
      - POSTGRES_PASSWORD=onidata
    ports:
      - 5432:5432
