# Generated by Django 4.2.1 on 2023-05-19 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loan_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="payment",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
