# Generated by Django 4.2.1 on 2023-05-19 22:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_loan_identifier_payment_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
